Add possibility to not store all the samples that leak memory
pkolaczk/latte pull request #87
Opened 2024-07-08 08:35 UTC by vponomaryov

It affects the possibility to generate report that requires data.
So, add new config option called `--generate-report` to cover the situation with memory leaks.

If it is set then we store all the samples as before and generate final report based on the stored data.
Side-effect - linear memory leaks.
If it is not set (default) then the samples data won't be stored and
final report won't be generated keeping stable memory consumption.

2024-07-14 14:27 UTC, pkolaczk requested changes
This looks to me like a too extreme user-facing change to workaround an edge-case problem. Generating the report is the major use case of `latte run`. This change here would turn latte into a dumb workload generator  (well, to some degree latte is a workload generation tool, but many people use it for the benchmarking and measuring capabilities as well). I'd rather keep the reports and make the memory leak problem smaller instead of turning off the reports.

The main issue is keeping histograms, not keeping the summary data in samples. The summaries are very small - this is just a couple of numbers. Histograms are the elephant in the room. 


So instead of disabling the whole report, could you try a bit less extreme solution - dropping histograms from `Sample` after computing the percentiles. And adding an option `--keep-histograms` to control this new behavior. That would require putting histograms under `Option` obviously.

This would keep 99% of functionality of reports, at the expense of not being able to do hdr logs later. But HDR logs are probably quite a niche feature (I used them once) so I'm ok with breaking it a bit. And I guess maybe the next step would be to add `--hdr-log` option directly to `run` - so we could eat the cake and have it too. Just dump the histograms to disk on the go, instead of keeping them till the end.


BTW  if you don't need the log / report, then why not set the sampling to a very large delay? You can collect one sample per hour and I guess the memory leak problem goes away even for runs taking weeks. See the `-s` option.

2024-07-15 11:28 UTC, vponomaryov commented
> This looks to me like a too extreme user-facing change to workaround an edge-case problem. Generating the report is the major use case of `latte run`. This change here would turn latte into a dumb workload generator (well, to some degree latte is a workload generation tool, but many people use it for the benchmarking and measuring capabilities as well). I'd rather keep the reports and make the memory leak problem smaller instead of turning off the reports.
> 
> The main issue is keeping histograms, not keeping the summary data in samples. The summaries are very small - this is just a couple of numbers. Histograms are the elephant in the room.
> 
> So instead of disabling the whole report, could you try a bit less extreme solution - dropping histograms from `Sample` after computing the percentiles. And adding an option `--keep-histograms` to control this new behavior. That would require putting histograms under `Option` obviously.
> 
> This would keep 99% of functionality of reports, at the expense of not being able to do hdr logs later. But HDR logs are probably quite a niche feature (I used them once) so I'm ok with breaking it a bit. And I guess maybe the next step would be to add `--hdr-log` option directly to `run` - so we could eat the cake and have it too. Just dump the histograms to disk on the go, instead of keeping them till the end.

It is much better than current approach, but still contradicts the idea of testing possible memory leaks in the underlying Scylla rust driver.
So, probably having 3 possible setups is the best solution here:
- Light reports without HDRs (default)
- Heavy reports with HDRs
- No reports, no memory leaks.

As of now, reworking this feature doesn't fit our schedule.

> BTW if you don't need the log / report, then why not set the sampling to a very large delay? You can collect one sample per hour and I guess the memory leak problem goes away even for runs taking weeks. See the `-s` option.

It is totally unacceptable in hour case to set huge sample intervals.
We don't use report files at all.
We stream output to our test framework and check exit code.
We view retries, when happened, number of it. Retries are tied to samples and their intervals.

In our case it is not `dumb` load generation,
it is exactly `smart` load generator (dozens of different parallel functions with their own rates) during which we introduce different failure injections and make sure load still works.

2024-07-17 16:26 UTC, pkolaczk commented
Fair enough. Then maybe just negate the default. What about making an option `--no-report`? But keep the report generation on by default. Because testing the driver for memory leaks is probably something only you do ;)

2024-08-09 19:24 UTC, pkolaczk commented
Ok, soon I'll have something that will address this problem in a better way.
We can have the report *and* constant memory use.

2024-08-11 08:03 UTC, pkolaczk commented
Closing this as this was superseded by #103

2024-08-11 08:03 UTC, closed without merging